// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnJv6AEiqFzvi_u1GXYpn0h885bjrGIGA',
    appId: '1:483912560165:web:73840f4ab63973e150d9cc',
    messagingSenderId: '483912560165',
    projectId: 'sos-safety-system-e6eae',
    authDomain: 'sos-safety-system-e6eae.firebaseapp.com',
    storageBucket: 'sos-safety-system-e6eae.firebasestorage.app',
    measurementId: 'G-QPRWG75XJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL21MpMCOaYLN_uOEBis6Rc-nUW2tQ9jI',
    appId: '1:483912560165:android:0f832355941b755350d9cc',
    messagingSenderId: '483912560165',
    projectId: 'sos-safety-system-e6eae',
    storageBucket: 'sos-safety-system-e6eae.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5OLz6mngMqsisHx9uE5A6-3HNCvp13gw',
    appId: '1:483912560165:ios:eea674c9bc410b7550d9cc',
    messagingSenderId: '483912560165',
    projectId: 'sos-safety-system-e6eae',
    storageBucket: 'sos-safety-system-e6eae.firebasestorage.app',
    iosBundleId: 'com.example.sosSafety',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5OLz6mngMqsisHx9uE5A6-3HNCvp13gw',
    appId: '1:483912560165:ios:eea674c9bc410b7550d9cc',
    messagingSenderId: '483912560165',
    projectId: 'sos-safety-system-e6eae',
    storageBucket: 'sos-safety-system-e6eae.firebasestorage.app',
    iosBundleId: 'com.example.sosSafety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnJv6AEiqFzvi_u1GXYpn0h885bjrGIGA',
    appId: '1:483912560165:web:208543517d18ddb550d9cc',
    messagingSenderId: '483912560165',
    projectId: 'sos-safety-system-e6eae',
    authDomain: 'sos-safety-system-e6eae.firebaseapp.com',
    storageBucket: 'sos-safety-system-e6eae.firebasestorage.app',
    measurementId: 'G-V1QVG9RMZ9',
  );
}
